# Generated by Django 4.0.1 on 2022-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingcode',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='trackingcode',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
