# Generated by Django 4.0.1 on 2022-02-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0003_remove_trackingcode_profile_id_trackingcode_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorslog',
            name='js_id',
        ),
    ]
