# Generated by Django 4.0.1 on 2022-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0004_remove_visitorslog_js_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorslog',
            name='web_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
