# Generated by Django 4.0.1 on 2022-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0005_visitorslog_web_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorslog',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
