# Generated by Django 4.0.1 on 2022-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0006_visitorslog_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorslog',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
