# Generated by Django 4.0.1 on 2022-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_code', '0007_visitorslog_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorslog',
            name='device_id',
            field=models.JSONField(null=True, verbose_name='device id'),
        ),
    ]
