# Generated by Django 4.0.1 on 2022-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplans',
            name='no_of_trial_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyplans',
            name='plan_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyplans',
            name='daily_email_limit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyplans',
            name='linkedIn_inmail_paid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyplans',
            name='linkedin_messages_free',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyplans',
            name='linkedin_messages_paid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyplans',
            name='weekly_connection_limit',
            field=models.CharField(max_length=20),
        ),
    ]
