# Generated by Django 4.0.1 on 2022-02-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plan', '0004_usersubscriptionpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplans',
            name='no_of_companies_to_identify',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyplans',
            name='no_of_tracking_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlyplans',
            name='no_of_website',
            field=models.IntegerField(default=1),
        ),
    ]
