# Generated by Django 4.0.1 on 2022-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plan', '0007_usersubscriptionpaymenthistory_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplans',
            name='is_trial_plan',
            field=models.BooleanField(default=False),
        ),
    ]
