# Generated by Django 4.0.1 on 2022-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plan', '0008_monthlyplans_is_trial_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyplans',
            old_name='per_month_charge',
            new_name='per_month_charge_in_dollar',
        ),
        migrations.AddField(
            model_name='monthlyplans',
            name='per_month_charge_in_pound',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
