# Generated by Django 4.0.1 on 2022-04-22 13:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_subscription_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_profile_image.jpg', force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='Profile_Images/%Y/%m/%d'),
        ),
    ]
